version: "3.9"
services:
  app:
    build: .
    container_name: backend_app
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/backend_db
      - NODE_ENV=development
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: backend_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
